version: '3.3'

services:

  #php service

  php:
      build:
         context: .
         dockerfile: Dockerfile
         args:
            - APP_ENV=${APP_ENV}
      environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=app
      working_dir: /var/www
      volumes:
        - ./:/var/www
      ports:
        - 5000:80  
      depends_on:
        - redis  


  #Database server
  

   #Redis Server
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - 6379:6379

volumes:
  db-data: ~